<?php

use Illuminate\Database\Seeder;

class PertanyaansTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pertanyaans = array(
            array('id_pertanyaan' => '1','id_jenis_pertanyaans' => '1','pertanyaan' => 'Jenis Kelamin?','id_judul' => '1','nomer_urut' => '1'),
            array('id_pertanyaan' => '2','id_jenis_pertanyaans' => '3','pertanyaan' => 'Tahun lahir','id_judul' => '1','nomer_urut' => '2'),
            array('id_pertanyaan' => '3','id_jenis_pertanyaans' => '5','pertanyaan' => 'Status pernikahan','id_judul' => '1','nomer_urut' => '3'),
            array('id_pertanyaan' => '4','id_jenis_pertanyaans' => '5','pertanyaan' => 'Jenis Sekolah Lanjutan Tingkat Atas (SLTA)?','id_judul' => '1','nomer_urut' => '4'),
            array('id_pertanyaan' => '5','id_jenis_pertanyaans' => '8','pertanyaan' => 'Dinegara mana lokasi SLTA anda?','id_judul' => '1','nomer_urut' => '6'),
            array('id_pertanyaan' => '6','id_jenis_pertanyaans' => '5','pertanyaan' => 'Jurusan yang anda ambil pada saat di SLTA?','id_judul' => '1','nomer_urut' => '7'),
            array('id_pertanyaan' => '7','id_jenis_pertanyaans' => '3','pertanyaan' => 'Tahun berapa anda lulus SLTA?','id_judul' => '1','nomer_urut' => '8'),
            array('id_pertanyaan' => '8','id_jenis_pertanyaans' => '1','pertanyaan' => 'Kebangsaan','id_judul' => '1','nomer_urut' => '9'),
            array('id_pertanyaan' => '9','id_jenis_pertanyaans' => '1','pertanyaan' => 'Apakah anda pernah bekerja sebelum kuliah di universitas?','id_judul' => '1','nomer_urut' => '10'),
            array('id_pertanyaan' => '10','id_jenis_pertanyaans' => '1','pertanyaan' => 'Jika ya, apa jenis pekerjaannya?','id_judul' => '1','nomer_urut' => '11'),
            array('id_pertanyaan' => '11','id_jenis_pertanyaans' => '3','pertanyaan' => 'Berapa lama anda melakukan pekerjaan tersebut?','id_judul' => '1','nomer_urut' => '12'),
            array('id_pertanyaan' => '12','id_jenis_pertanyaans' => '8','pertanyaan' => 'Berapa bulan yang anda habiskan untuk aktivitas di bawah ini setelah lulus SLTA dan sebelum masuk kuliah?','id_judul' => '1','nomer_urut' => '13'),
            array('id_pertanyaan' => '13','id_jenis_pertanyaans' => '6','pertanyaan' => 'Apa latar belakang pendidikan ibu anda?','id_judul' => '1','nomer_urut' => '14'),
            array('id_pertanyaan' => '14','id_jenis_pertanyaans' => '0','pertanyaan' => 'Dari fakultas/program studi dan departemen apa anda lulus pada tahun 2011?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '15','id_jenis_pertanyaans' => '0','pertanyaan' => 'Kapan anda masuk dan lulus kuliah di fakultas tersebut?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '16','id_jenis_pertanyaans' => '0','pertanyaan' => 'Apakah anda lulus tepat waktu?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '17','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa besar alasan-alasan di bawah ini menyebabkan ketidaktepatan masa studi anda?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '18','id_jenis_pertanyaans' => '0','pertanyaan' => 'Selama kuliah kebanyakan anda tinggal ………','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '19','id_jenis_pertanyaans' => '0','pertanyaan' => 'Siapa yang terutama membayar uang kuliah anda?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '20','id_jenis_pertanyaans' => '0','pertanyaan' => 'Berapa nilai IPK (Indeks Prestasi Kumulatif) anda?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '21','id_jenis_pertanyaans' => '0','pertanyaan' => 'Selama kuliah, apakah anda menjadi anggota dari suatu organisasi (sosial, pemuda, organisasi keagamaan) di dalam atau di luar kampus?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '22','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa aktif anda di organisasi tersebut?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '23','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pada saat anda kuliah di perguruan tinggi, apakah anda mengambil kursus atau pendidikan tambahan?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '24','id_jenis_pertanyaans' => '0','pertanyaan' => 'Menurut anda seberapa besar penekanan pada aspek-aspek pembelajaran di bawah ini dilaksanakan di program studi anda?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '25','id_jenis_pertanyaans' => '0','pertanyaan' => 'Bagaimana penilaian anda terhadap aspek belajar mengajar di bawah ini?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '26','id_jenis_pertanyaans' => '0','pertanyaan' => 'Selama anda kuliah di Ubaya, bagaimana pendapat anda terhadap kondisi  fasilitas belajar di bawah ini?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '27','id_jenis_pertanyaans' => '0','pertanyaan' => 'Bagaimana penilaian anda terhadap pengalaman belajar di bawah ini?','id_judul' => '2','nomer_urut' => '0'),
            array('id_pertanyaan' => '28','id_jenis_pertanyaans' => '1','pertanyaan' => 'Pada saat baru lulus, apakah anda bersedia bekerja/ditempatkan di daerah?','id_judul' => '3','nomer_urut' => '1'),
            array('id_pertanyaan' => '29','id_jenis_pertanyaans' => '5','pertanyaan' => 'Bila tidak bersedia ditempatkan di daerah, apa alasan utamanya?','id_judul' => '3','nomer_urut' => '2'),
            array('id_pertanyaan' => '30','id_jenis_pertanyaans' => '1','pertanyaan' => 'Kapan anda mulai mencari pekerjaan? (Mohon pekerjaan sambilan tidak dimasukkan)','id_judul' => '3','nomer_urut' => '3'),
            array('id_pertanyaan' => '31','id_jenis_pertanyaans' => '6','pertanyaan' => 'Bagaimana anda mencari pekerjaan setelah lulus? Jawaban bisa lebih dari satu','id_judul' => '3','nomer_urut' => '4'),
            array('id_pertanyaan' => '32','id_jenis_pertanyaans' => '6','pertanyaan' => 'Berdasarkan persepsi anda, seberapa pentingkah aspek-aspek di bawah ini bagi perusahaan/instansi dalam melakukan penerimaan pegawai baru? (Jawaban bisa lebih dari satu)
          ','id_judul' => '3','nomer_urut' => '5'),
            array('id_pertanyaan' => '33','id_jenis_pertanyaans' => '4','pertanyaan' => 'Berapa perusahaan/instansi/institusi yang sudah anda lamar (lewat surat atau e-mail) sebelum anda memeroleh pekerjaan pertama?','id_judul' => '3','nomer_urut' => '6'),
            array('id_pertanyaan' => '34','id_jenis_pertanyaans' => '0','pertanyaan' => 'Berapa bulan waktu yang dihabiskan (sebelum dan sesudah kelulusan) untuk memeroleh pekerjaan pertama?','id_judul' => '3','nomer_urut' => '7'),
            array('id_pertanyaan' => '35','id_jenis_pertanyaans' => '0','pertanyaan' => 'Berapa banyak perusahaan/instansi/institusi yang merespons lamaran anda?','id_judul' => '3','nomer_urut' => '8'),
            array('id_pertanyaan' => '36','id_jenis_pertanyaans' => '0','pertanyaan' => 'Apa alasan utama anda tidak mencari pekerjaan setelah lulus kuliah?','id_judul' => '3','nomer_urut' => '9'),
            array('id_pertanyaan' => '37','id_jenis_pertanyaans' => '0','pertanyaan' => 'Bagaimana cara anda mendapatkan pekerjaan pertama? Hanya satu jawaban','id_judul' => '3','nomer_urut' => '10'),
            array('id_pertanyaan' => '38','id_jenis_pertanyaans' => '0','pertanyaan' => 'Aspek apa yang menjadi pertimbangan utama anda dalam memilih pekerjaan pertama? Jawaban bisa lebih dari satu','id_judul' => '3','nomer_urut' => '11'),
            array('id_pertanyaan' => '39','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pada saat anda kuliah dan setelah lulus, apakah anda mengambil kursus dalam rangka menyiapkan atau meningkatkan kemampuan anda untuk persiapan bekerja?','id_judul' => '3','nomer_urut' => '12'),
            array('id_pertanyaan' => '40','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jenis kursus apa yang anda ambil SETELAH anda lulus dari perguruan tinggi? Jawaban bisa lebih dari satu','id_judul' => '3','nomer_urut' => '13'),
            array('id_pertanyaan' => '41','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa besar peran kursus tersebut dalam hal-hal di bawah ini?','id_judul' => '3','nomer_urut' => '14'),
            array('id_pertanyaan' => '42','id_jenis_pertanyaans' => '0','pertanyaan' => 'Apakah anda merasa perlu untuk meningkatkan kompetensi anda dengan mengambil kursus lagi?','id_judul' => '3','nomer_urut' => '15'),
            array('id_pertanyaan' => '43','id_jenis_pertanyaans' => '0','pertanyaan' => 'Apakah anda bekerja saat ini (termasuk kerja sambilan dan wirausaha)?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '44','id_jenis_pertanyaans' => '0','pertanyaan' => 'Bagaimana anda menggambarkan situasi anda saat ini? Jawaban bisa lebih dari satu','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '45','id_jenis_pertanyaans' => '0','pertanyaan' => 'Apakah anda aktif mencari pekerjaan dalam 4 minggu terakhir? Pilih satu jawaban','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '46','id_jenis_pertanyaans' => '0','pertanyaan' => 'Berapa perusahaan/instansi/institusi yang telah anda masuki untuk bekerja (termasuk perusahaan sendiri) sejak anda lulus dari perguruan tinggi?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '47','id_jenis_pertanyaans' => '0','pertanyaan' => 'Apa jenis perusahaan/instansi/institusi tempat anda bekerja sekarang?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '50','id_jenis_pertanyaans' => '0','pertanyaan' => 'Tempat anda bekerja saat ini bergerak di bidang apa? (Klasifikasi Baku Lapangan Usaha Indonesia, Kemnakertrans, 2009)','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '51','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jelaskan tugas-tugas utama dalam pekerjaan anda sekarang?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '52','id_jenis_pertanyaans' => '0','pertanyaan' => 'Berapa jam rata-rata per minggu anda bekerja?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '53','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda menjalankan perusahaan sendiri, apa karakteristik bidang usaha yang sedang anda jalani saat ini? Jawaban bisa lebih dari satu','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '54','id_jenis_pertanyaans' => '0','pertanyaan' => 'Kira-kira berapa pendapatan anda setiap bulannya?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '55','id_jenis_pertanyaans' => '0','pertanyaan' => 'Dalam setahun terakhir ini apakah anda melakukan perjalanan ke luar negeri dalam rangka bisnis/profesi?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '56','id_jenis_pertanyaans' => '0','pertanyaan' => 'Berapa persen dari waktu kerja anda yang memiliki hubungan internasional?','id_judul' => '4','nomer_urut' => '0'),
            array('id_pertanyaan' => '57','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pada saat lulus, sejauh mana kompetensi di bawah ini anda kuasai? (A)
          Pada saat lulus, sejauh mana kontribusi yang sudah perguruan tinggi berikan dalam hal kompetensi di bawah ini? (B)','id_judul' => '6','nomer_urut' => '0'),
            array('id_pertanyaan' => '58','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pada saat anda lulus dari perguruan tinggi, bagaimana tingkat kemampuan bahasa asing anda?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '59','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa besar kontribusi perguruan tinggi dalam penguasaan bahasa asing?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '60','id_jenis_pertanyaans' => '0','pertanyaan' => 'Sejauh mana program studi anda bermanfaat untuk hal-hal di bawah ini?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '61','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa besar peran kompetensi yang telah diperoleh di perguruan tinggi berikut ini dalam melaksanakan pekerjaan anda?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '62','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa erat hubungan antara bidang studi dengan pekerjaan anda?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '63','id_jenis_pertanyaans' => '0','pertanyaan' => 'Tingkat pendidikan apa yang paling tepat/sesuai untuk pekerjaan anda saat ini?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '64','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika menurut anda pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?  Jawaban bisa lebih dari satu','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '65','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda mendapat kesempatan untuk kembali ke masa lalu, apakah anda akan tetap memilih Ubaya sebagai tempat kuliah?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '66','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda tidak memilih Ubaya kembali sebagai tempat kuliah, apa alasan utamanya?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '67','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda mendapat kesempatan untuk kembali ke masa lalu, apakah anda akan tetap memilih fakultas yang sama?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '68','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda tidak memilih fakultas yang sama, apa alasan utamanya?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '69','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda mendapat kesempatan untuk kembali ke masa lalu, apakah anda akan tetap memilih departemen/program studi yang sama?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '70','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda tidak memilih departemen/program studi yang sama, apa alasan utamanya?','id_judul' => '5','nomer_urut' => '0'),
            array('id_pertanyaan' => '71','id_jenis_pertanyaans' => '4','pertanyaan' => 'Apa nama SLTA anda ? ','id_judul' => '1','nomer_urut' => '5'),
            array('id_pertanyaan' => '72','id_jenis_pertanyaans' => '3','pertanyaan' => 'Dikota mana lokasi SLTA anda? ','id_judul' => '1','nomer_urut' => '0'),
            array('id_pertanyaan' => '73','id_jenis_pertanyaans' => '1','pertanyaan' => 'Pendidikan lain/training/magang ','id_judul' => '1','nomer_urut' => '0'),
            array('id_pertanyaan' => '74','id_jenis_pertanyaans' => '1','pertanyaan' => 'Bekerja/wiraswasta ','id_judul' => '1','nomer_urut' => NULL),
            array('id_pertanyaan' => '75','id_jenis_pertanyaans' => '1','pertanyaan' => 'Mengurus anak, mengurus keluarga','id_judul' => '1','nomer_urut' => NULL),
            array('id_pertanyaan' => '76','id_jenis_pertanyaans' => '1','pertanyaan' => 'Wajib militer','id_judul' => '1','nomer_urut' => NULL),
            array('id_pertanyaan' => '77','id_jenis_pertanyaans' => '1','pertanyaan' => 'Tidak bekerja, mencari pekerjaan','id_judul' => '1','nomer_urut' => NULL),
            array('id_pertanyaan' => '78','id_jenis_pertanyaans' => '1','pertanyaan' => 'Apa latar belakang pendidikan Ayah anda ','id_judul' => '1','nomer_urut' => NULL),
            array('id_pertanyaan' => '79','id_jenis_pertanyaans' => '5','pertanyaan' => 'fakultas ?','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '80','id_jenis_pertanyaans' => '2','pertanyaan' => 'program studi ?','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '81','id_jenis_pertanyaans' => '4','pertanyaan' => 'Registrasi study ?','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '82','id_jenis_pertanyaans' => '4','pertanyaan' => 'Yudisium study ?','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '83','id_jenis_pertanyaans' => '4','pertanyaan' => 'Alasan keuangan ?','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '84','id_jenis_pertanyaans' => '4','pertanyaan' => 'Tidak lulus ujian (banyak mengulang)','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '85','id_jenis_pertanyaans' => '4','pertanyaan' => 'Penulisan skripsi lambat','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '86','id_jenis_pertanyaans' => '4','pertanyaan' => 'Alasan keluarga','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '87','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kesehatan','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '88','id_jenis_pertanyaans' => '4','pertanyaan' => 'Lainnya terlalu banyak ikut campur organisasi','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '89','id_jenis_pertanyaans' => '4','pertanyaan' => 'Lainnya terlalu banyak ikut campur organisasi(Alasanya)','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '90','id_jenis_pertanyaans' => '1','pertanyaan' => 'Selama kuliah, apakah anda menjadi anggota dari suatu organisasi (sosial, pemuda, organisasi keagamaan) di dalam atau di luar kampus?(Alasan ya)','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '91','id_jenis_pertanyaans' => '4','pertanyaan' => 'tuliskan nama kursus atau pendidikan tambahan tersebut ?','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '92','id_jenis_pertanyaans' => '4','pertanyaan' => 'Perkuliahan','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '93','id_jenis_pertanyaans' => '4','pertanyaan' => 'Demonstrasi (peragaan)','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '94','id_jenis_pertanyaans' => '4','pertanyaan' => 'Partisipasi dalam proyek riset ','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '95','id_jenis_pertanyaans' => '4','pertanyaan' => 'Magang','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '96','id_jenis_pertanyaans' => '4','pertanyaan' => 'Praktikum/kerja lapangan','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '97','id_jenis_pertanyaans' => '4','pertanyaan' => 'Diskusi','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '98','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kesempatan untuk berinteraksi dengan dosen-dosen di luar jadwal kuliah','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '99','id_jenis_pertanyaans' => '4','pertanyaan' => 'Pembimbingan akademik','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '100','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kesempatan berpartisipasi dalam proyek riset','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '101','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kondisi umum belajar mengajar','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '102','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kesempatan untuk memasuki dan menjadi bagian dari jejaring ilmiah profesional ','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '103','id_jenis_pertanyaans' => '4','pertanyaan' => 'Lainnya','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '104','id_jenis_pertanyaans' => '4','pertanyaan' => 'Fasililtas layanan kesehatan','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '105','id_jenis_pertanyaans' => '4','pertanyaan' => 'Perpustakaan','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '106','id_jenis_pertanyaans' => '4','pertanyaan' => 'Teknologi Informasi dan Komunikasi','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '107','id_jenis_pertanyaans' => '4','pertanyaan' => 'Modul belajar','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '108','id_jenis_pertanyaans' => '4','pertanyaan' => 'Ruang belajar','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '109','id_jenis_pertanyaans' => '4','pertanyaan' => 'Laboratorium','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '110','id_jenis_pertanyaans' => '4','pertanyaan' => 'Variasi matakuliah yang ditawarkanVariasi matakuliah yang ditawarkan','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '111','id_jenis_pertanyaans' => '4','pertanyaan' => 'Akomodasi','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '112','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kantin','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '113','id_jenis_pertanyaans' => '4','pertanyaan' => 'Pusat kegiatan mahasiswa dan fasilitasnya, ruang rekreasi','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '114','id_jenis_pertanyaans' => '4','pertanyaan' => 'Pembelajaran di kelas','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '115','id_jenis_pertanyaans' => '4','pertanyaan' => 'Magang/kerja lapangan/praktikum','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '116','id_jenis_pertanyaans' => '4','pertanyaan' => 'Pengabdian dan penjangkauan masyarakat','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '117','id_jenis_pertanyaans' => '4','pertanyaan' => 'Pelaksanaan riset/penulisan skripsi','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '118','id_jenis_pertanyaans' => '4','pertanyaan' => 'Organisasi kemahasiswaan','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '119','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kegiatan ekstrakurikuler','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '120','id_jenis_pertanyaans' => '4','pertanyaan' => 'Rekreasi dan olahraga','id_judul' => '2','nomer_urut' => NULL),
            array('id_pertanyaan' => '121','id_jenis_pertanyaans' => '4','pertanyaan' => 'Berapa banyak perusahaan/instansi/institusi yang mengundang anda untuk wawancara?','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '122','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kira-kira berapa bulan sebelum lulus','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '123','id_jenis_pertanyaans' => '4','pertanyaan' => 'Kira-kira berapa bulan setelah lulus','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '124','id_jenis_pertanyaans' => '4','pertanyaan' => 'Memulai pekerjaan','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '125','id_jenis_pertanyaans' => '4','pertanyaan' => 'Mendapatkan pekerjaan yang memuaskan/sesuai harapan','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '126','id_jenis_pertanyaans' => '4','pertanyaan' => 'Memenuhi persyaratan kompetensi untuk bekerja','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '127','id_jenis_pertanyaans' => '4','pertanyaan' => 'Meningkatkan keterampilan kewirausahaan','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '128','id_jenis_pertanyaans' => '4','pertanyaan' => 'Pengembangan diri','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '129','id_jenis_pertanyaans' => '4','pertanyaan' => 'Karir di masa depan','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '130','id_jenis_pertanyaans' => '4','pertanyaan' => 'Lainnya','id_judul' => '3','nomer_urut' => NULL),
            array('id_pertanyaan' => '131','id_jenis_pertanyaans' => '0','pertanyaan' => 'Tugas-tugas utama sesuai kontrak','id_judul' => '4','nomer_urut' => NULL),
            array('id_pertanyaan' => '132','id_jenis_pertanyaans' => '0','pertanyaan' => 'Tugas-tugas tambahan di luar tugas utama (termasuk lembur dibayar dan tidak dibayar)','id_judul' => '4','nomer_urut' => NULL),
            array('id_pertanyaan' => '133','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pekerjaan lainnya (pekerjaan kedua, pekerjaan sambilan, dll)','id_judul' => '4','nomer_urut' => NULL),
            array('id_pertanyaan' => '134','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jumlah jam kerja total (hanya untuk yang wiraswasta)','id_judul' => '4','nomer_urut' => NULL),
            array('id_pertanyaan' => '135','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Pengetahuan di bidang atau disiplin ilmu anda','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '136','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Pengetahuan di luar bidang atau disiplin ilmu anda ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '137','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Pengetahuan umum ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '138','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Ketrampilan internet ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '139','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Ketrampilan komputer ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '140','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Berpikir kritis ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '141','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Ketrampilan riset ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '142','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan belajar ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '143','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan berkomunikasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '144','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Bekerja di bawah tekanan ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '145','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Manajemen waktu ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '146','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Bekerja secara mandiri ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '147','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Bekerja dalam tim/bekerjasama dengan orang lain ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '148','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan dalam memecahkan masalah ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '149','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Negosiasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '150','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan analisis ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '151','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Toleransi','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '152','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan adaptasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '153','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Loyalitas dan integritas ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '154','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Bekerja dengan orang yang berbeda budaya maupun latar belakang','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '155','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kepemimpinan','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '156','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan dalam memegang tanggungjawab','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '157','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Inisiatif','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '158','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Manajemen proyek/program ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '159','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan untuk memresentasikan ide/produk/laporan','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '160','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan dalam menulis laporan, memo dan dokumen','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '161','id_jenis_pertanyaans' => '0','pertanyaan' => '(A).Kemampuan untuk terus belajar sepanjang hayat','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '165','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Pengetahuan di bidang atau disiplin ilmu anda','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '166','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Pengetahuan di luar bidang atau disiplin ilmu anda ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '167','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Pengetahuan umum ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '168','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Ketrampilan internet ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '169','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Ketrampilan komputer ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '170','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Berpikir kritis ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '171','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Ketrampilan riset ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '172','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan belajar ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '173','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan berkomunikasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '174','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Bekerja di bawah tekanan ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '175','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Manajemen waktu ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '176','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Bekerja secara mandiri ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '177','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Bekerja dalam tim/bekerjasama dengan orang lain ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '178','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan dalam memecahkan masalah ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '179','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Negosiasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '180','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan analisis ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '181','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Toleransi','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '182','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan adaptasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '183','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Loyalitas dan integritas ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '184','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Bekerja dengan orang yang berbeda budaya maupun latar belakang','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '185','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kepemimpinan','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '186','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan dalam memegang tanggungjawab','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '187','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Inisiatif','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '188','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Manajemen proyek/program ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '189','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan untuk memresentasikan ide/produk/laporan','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '190','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan dalam menulis laporan, memo dan dokumen','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '191','id_jenis_pertanyaans' => '0','pertanyaan' => '(b).Kemampuan untuk terus belajar sepanjang hayat','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '192','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pada saat anda lulus dari perguruan tinggi, bagaimana tingkat kemampuan bahasa asing anda? ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '193','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa besar kontribusi perguruan tinggi dalam penguasaan bahasa asing? ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '194','id_jenis_pertanyaans' => '0','pertanyaan' => 'Memulai pekerjaan?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '195','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pembelajaran lanjut dalam pekerjaan?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '196','id_jenis_pertanyaans' => '0','pertanyaan' => 'Kinerja dalam menjalankan tugas?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '197','id_jenis_pertanyaans' => '5','pertanyaan' => 'Karir di masa depan?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '198','id_jenis_pertanyaans' => '0','pertanyaan' => 'Pengembangan diri?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '199','id_jenis_pertanyaans' => '0','pertanyaan' => 'Meningkatkan ketrampilan kewirausahaan?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '200','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Pengetahuan di bidang atau disiplin ilmu anda','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '201','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Pengetahuan di luar bidang atau disiplin ilmu anda ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '202','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Pengetahuan umum ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '203','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Ketrampilan internet ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '204','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Ketrampilan komputer ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '205','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Berpikir kritis ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '206','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Ketrampilan riset ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '207','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan belajar ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '208','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan berkomunikasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '209','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Bekerja di bawah tekanan ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '210','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Manajemen waktu ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '211','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Bekerja secara mandiri ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '212','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Bekerja dalam tim/bekerjasama dengan orang lain ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '213','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan dalam memecahkan masalah ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '214','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Negosiasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '215','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan analisis ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '216','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Toleransi','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '217','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan adaptasi ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '218','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Loyalitas dan integritas ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '219','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Bekerja dengan orang yang berbeda budaya maupun latar belakang','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '220','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kepemimpinan','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '221','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan dalam memegang tanggungjawab','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '222','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Inisiatif','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '223','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Manajemen proyek/program ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '224','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan untuk memresentasikan ide/produk/laporan','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '225','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan dalam menulis laporan, memo dan dokumen','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '226','id_jenis_pertanyaans' => '0','pertanyaan' => 'E5.Kemampuan untuk terus belajar sepanjang hayat','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '227','id_jenis_pertanyaans' => '0','pertanyaan' => 'Seberapa erat hubungan antara bidang studi dengan pekerjaan anda?   ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '228','id_jenis_pertanyaans' => '0','pertanyaan' => 'Tingkat pendidikan apa yang paling tepat/sesuai untuk pekerjaan anda saat ini?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '229','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika menurut anda pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?  Jawaban bisa lebih dari satu ','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '230','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda mendapat kesempatan untuk kembali ke masa lalu, apakah anda akan tetap memilih Ubaya sebagai tempat kuliah?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '231','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda tidak memilih Ubaya kembali sebagai tempat kuliah, apa alasan utamanya?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '232','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda mendapat kesempatan untuk kembali ke masa lalu, apakah anda akan tetap memilih fakultas yang sama?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '233','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda tidak memilih fakultas yang sama, apa alasan utamanya?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '234','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda mendapat kesempatan untuk kembali ke masa lalu, apakah anda akan tetap memilih departemen/program studi yang sama?','id_judul' => '5','nomer_urut' => NULL),
            array('id_pertanyaan' => '235','id_jenis_pertanyaans' => '0','pertanyaan' => 'Jika anda tidak memilih departemen/program studi yang sama, apa alasan utamanya?','id_judul' => '5','nomer_urut' => NULL)
          );

        foreach ($pertanyaans as $pertanyaan):
            App\Pertanyaan::create([
                'pertanyaan' => $pertanyaan['pertanyaan'],
                'kuesioner_id' => $pertanyaan['id_judul'],
                'nomor_urut' => $pertanyaan['nomer_urut']
            ]);
        endforeach;
    }
}
